# Use an official GCC base image
FROM gcc:latest

# Set the working directory
WORKDIR /app

# Create an empty C++ code file named main.cpp
RUN touch main.cpp

# Set the C++ code as an environment variable
ENV CODE ""

# Set the input data as an environment variable
ENV INPUT_DATA ""

# Copy the code to main.cpp and run the code with provided inputs
CMD ["sh", "-c", "echo \"$CODE\" > main.cpp && echo \"$INPUT_DATA\" > input.txt && g++ -o main main.cpp && ./main < input.txt"]
